#!/bin/bash
set -e
DIR="$(cd "$(dirname "$0")" && pwd)"

echo "==============================="
echo "  Orbital Schema Test Suite"
echo "==============================="
echo ""
bash "$DIR/test-opportunity-schema.sh"
echo ""
bash "$DIR/test-contribution-schema.sh"
echo ""
bash "$DIR/test-synthesis-schema.sh"
echo ""
bash "$DIR/test-review-schema.sh"
echo ""
bash "$DIR/test-context-schema.sh"
echo ""
bash "$DIR/test-dot-vote-schema.sh"
echo ""
bash "$DIR/test-evidence-schema.sh"
echo ""
echo "==============================="
echo "  ALL SCHEMA TESTS PASSED"
echo "==============================="
